package com.wd.tech.greendao;

import java.util.Map;

import org.greenrobot.greendao.AbstractDao;
import org.greenrobot.greendao.AbstractDaoSession;
import org.greenrobot.greendao.database.Database;
import org.greenrobot.greendao.identityscope.IdentityScopeType;
import org.greenrobot.greendao.internal.DaoConfig;

import com.wd.tech.bean.FindConversationList;
import com.wd.tech.bean.LoginUserInfoBean;

import com.wd.tech.greendao.FindConversationListDao;
import com.wd.tech.greendao.LoginUserInfoBeanDao;

// THIS CODE IS GENERATED BY greenDAO, DO NOT EDIT.

/**
 * {@inheritDoc}
 * 
 * @see org.greenrobot.greendao.AbstractDaoSession
 */
public class DaoSession extends AbstractDaoSession {

    private final DaoConfig findConversationListDaoConfig;
    private final DaoConfig loginUserInfoBeanDaoConfig;

    private final FindConversationListDao findConversationListDao;
    private final LoginUserInfoBeanDao loginUserInfoBeanDao;

    public DaoSession(Database db, IdentityScopeType type, Map<Class<? extends AbstractDao<?, ?>>, DaoConfig>
            daoConfigMap) {
        super(db);

        findConversationListDaoConfig = daoConfigMap.get(FindConversationListDao.class).clone();
        findConversationListDaoConfig.initIdentityScope(type);

        loginUserInfoBeanDaoConfig = daoConfigMap.get(LoginUserInfoBeanDao.class).clone();
        loginUserInfoBeanDaoConfig.initIdentityScope(type);

        findConversationListDao = new FindConversationListDao(findConversationListDaoConfig, this);
        loginUserInfoBeanDao = new LoginUserInfoBeanDao(loginUserInfoBeanDaoConfig, this);

        registerDao(FindConversationList.class, findConversationListDao);
        registerDao(LoginUserInfoBean.class, loginUserInfoBeanDao);
    }
    
    public void clear() {
        findConversationListDaoConfig.clearIdentityScope();
        loginUserInfoBeanDaoConfig.clearIdentityScope();
    }

    public FindConversationListDao getFindConversationListDao() {
        return findConversationListDao;
    }

    public LoginUserInfoBeanDao getLoginUserInfoBeanDao() {
        return loginUserInfoBeanDao;
    }

}
